// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'folder_model.mapper.dart'; ///same name of file

/// class and constructor and with dame name
@MappableClass()
class FolderModel with FolderModelMappable {
  final String? id;
  final String name;
  final String? desc;
  final String? color;
  final String? parent_folder;
  final String? user_id;
  final String? created_at;


  FolderModel({this.id, required this.name, this.desc,
    this.color, this.parent_folder,
    this.user_id,
  this.created_at});
}