// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'signup_model.mapper.dart';

@MappableClass()
class SignupModel with SignupModelMappable {
  SignupModel();
}
