// This file is "model.dart"
// ignore_for_file: non_constant_identifier_names

import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'create_bookmarks_model.mapper.dart';

///same name of file

/// class and constructor and with dame name
@MappableClass()
class CreateBookmarksModel with CreateBookmarksModelMappable {
  final String url;
  final String desc;
  final String content_type;
  final bool is_ticked;
  final String folder_id;

  CreateBookmarksModel({
    required this.url,
    required this.desc,
    required this.content_type,
    required this.is_ticked,
    required this.folder_id,
  });
}
