// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'update_bookmarks_model.mapper.dart'; ///same name of file

/// class and constructor and with dame name
@MappableClass()
class UpdateBookmarksModel with UpdateBookmarksModelMappable {
  final String id;
  final String url;
  final String desc;
  final String content_type;
  final bool is_ticked;
  final String folder_id;


  UpdateBookmarksModel({ required this.id,
    required this.url,required this.desc,required this.content_type,
    required this.is_ticked ,required this.folder_id
  });


}