// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'update_folder_model.mapper.dart'; ///same name of file

/// class and constructor and with dame name
@MappableClass()
class UpdateFolderModel with UpdateFolderModelMappable {
  final String id;
  final String name;
  final String? desc;
  final String? color;



  UpdateFolderModel({ required this.id, required this.name, this.desc,
    this.color,
  });


}