// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'auth_input.mapper.dart';

@MappableClass()
class AuthInput with AuthInputMappable {
  final String email;
  final String password;

  AuthInput({required this.email, required this.password});
}
