// This file is "model.dart"
// ignore_for_file: non_constant_identifier_names

import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'bookmarks_model.mapper.dart';

///same name of file

/// class and constructor and with dame name
@MappableClass()
class BookmarksModel with BookmarksModelMappable {
  final String url;
  final String desc;
  final String content_type;
  final bool is_ticked;
  final String folder_id;
  final String user_id;
  final String id;
  final String created_at;

  BookmarksModel({
    required this.user_id,
    required this.id,
    required this.created_at,
    required this.url,
    required this.desc,
    required this.content_type,
    required this.is_ticked,
    required this.folder_id,
  });
}
