// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'create_folder_model.mapper.dart'; ///same name of file

/// class and constructor and with dame name
@MappableClass()
class CreateFolderModel with CreateFolderModelMappable {
  final String name;
  final String? desc;
  final String? color;
//  final String? parent_folder;



  CreateFolderModel({ required this.name, this.desc,
    this.color, //this.parent_folder,
  });


}