// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'auth_model.mapper.dart';

@MappableClass()
class AuthModel with AuthModelMappable {
  final String token;

  AuthModel(this.token);
}
